language: python
python:
  - "3.6"
sudo: required
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
addons:
  ssh_known_hosts: splitgraph.com
script:
  - './.ci/script.sh'
after_success:
  - './.ci/after_success.sh'
