nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.js
    spec: "https://raw.githubusercontent.com/milesforks/yarn-plugin-workspace-lockfile/main/packages/plugin/bundles/%40yarnpkg/plugin-workspace-lockfile.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/plugin-interactive-tools/2.2.0/packages/plugin-interactive-tools/bin/%40yarnpkg/plugin-interactive-tools.js"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: "https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/plugin-constraints/2.2.0/packages/plugin-constraints/bin/%40yarnpkg/plugin-constraints.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/plugin-workspace-tools/2.2.0/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js"

yarnPath: .yarn/releases/yarn-berry.js
